### ISSUE TITLE
Adding streams with seperate url and key

### ISSUE THREAD

**Issue by tomdevlive** [NightStrang6r/Restreamer#1]
First of all, this is a great app and thank you for making it. I had a question, how do I add a stream that isnt just one value 'url+key', but instead it's the url and key separately. IS there a way to add those two things or does this app only work with destinations that have the url and key combined?

**Comment by NightStrang6r** [comment]
Hello. As far as I know, RTMP does not have a separate field for passing key. Key is always passed in a URL. For example, YouTube also provides a link and a key separately. But in fact, in the programs they are written like this: rtmp://a.rtmp.youtube.com/live2/YOUR_YOUTUBE_KEY
So just include your key in the link like in the example above.
